-- Aplicar como administrador de la base compartida antes de reiniciar los servicios.
BEGIN;
CREATE TABLE IF NOT EXISTS supporters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles(id),
    worker_id BIGINT NOT NULL REFERENCES field_workers(id),
    name TEXT NOT NULL, phone TEXT NOT NULL, voter_key TEXT NOT NULL,
    state TEXT NOT NULL, municipality TEXT NOT NULL,
    electoral_section TEXT NOT NULL DEFAULT '',
    registration_consent INTEGER NOT NULL CHECK(registration_consent=1),
    messaging_consent INTEGER NOT NULL CHECK(messaging_consent IN (0,1)),
    source_chat_id BIGINT NOT NULL, source_message_id BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS'),
    UNIQUE(profile_id,phone), UNIQUE(profile_id,voter_key), UNIQUE(source_chat_id,source_message_id)
);
CREATE TABLE IF NOT EXISTS supporter_sessions (
    worker_id BIGINT PRIMARY KEY REFERENCES field_workers(id),
    profile_id BIGINT NOT NULL REFERENCES profiles(id),
    started_at BIGINT NOT NULL, expires_at BIGINT NOT NULL
);
INSERT INTO field_permissions VALUES
    ('supporters.submit','Registrar simpatizantes'),
    ('supporters.view','Consultar catálogo de simpatizantes') ON CONFLICT DO NOTHING;
INSERT INTO field_role_permissions VALUES
    ('field','supporters.submit','own'), ('field','supporters.view','own'),
    ('supervisor','supporters.submit','own'), ('supervisor','supporters.view','team'),
    ('coordinator','supporters.submit','own'), ('coordinator','supporters.view','team'),
    ('director','supporters.view','campaign'),
    ('administrator','supporters.submit','all'), ('administrator','supporters.view','all') ON CONFLICT DO NOTHING;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='go2win_owner') THEN
        ALTER TABLE supporters OWNER TO go2win_owner;
        ALTER TABLE supporter_sessions OWNER TO go2win_owner;
    END IF;
END $$;
COMMIT;
