BEGIN;
CREATE TABLE IF NOT EXISTS field_needs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles(id),
    worker_id BIGINT NOT NULL REFERENCES field_workers(id),
    state TEXT NOT NULL, municipality TEXT NOT NULL, electoral_section TEXT NOT NULL,
    description TEXT NOT NULL CHECK(length(description) BETWEEN 1 AND 3000),
    origin TEXT NOT NULL CHECK(origin IN ('detectada','comentada')),
    source_chat_id BIGINT NOT NULL, source_message_id BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS'),
    UNIQUE(source_chat_id,source_message_id)
);
CREATE TABLE IF NOT EXISTS field_need_sessions (
    worker_id BIGINT PRIMARY KEY REFERENCES field_workers(id),
    profile_id BIGINT NOT NULL REFERENCES profiles(id),
    started_at BIGINT NOT NULL, expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS field_needs_territory_idx ON field_needs(profile_id,state,municipality,electoral_section);
INSERT INTO field_permissions VALUES ('needs.submit','Registrar necesidades territoriales'),
    ('needs.view','Consultar necesidades territoriales') ON CONFLICT DO NOTHING;
INSERT INTO field_role_permissions VALUES
    ('field','needs.submit','own'), ('field','needs.view','own'),
    ('coordinator','needs.view','campaign'), ('director','needs.view','campaign'),
    ('administrator','needs.submit','all'), ('administrator','needs.view','all') ON CONFLICT DO NOTHING;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='go2win_owner') THEN
        ALTER TABLE field_needs OWNER TO go2win_owner;
        ALTER TABLE field_need_sessions OWNER TO go2win_owner;
    END IF;
END $$;
COMMIT;
